In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Numpy merupakan library python digunakan untuk komputasi matriks. Matplotlib merupakan library python untuk presentasi data berupa grafik atau plot.

In [8]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [9]:
print(x)

[['Netherland' 40.0 75000.0]
 ['England' 32.0 54000.0]
 ['Sweden' 25.0 55000.0]
 ['Scotland' 36.0 60000.0]
 ['England' 50.0 nan]
 ['Netherland' 37.0 57000.0]
 ['Sweden' nan 59000.0]
 ['Scotland' 46.0 80000.0]
 ['England' 42.0 90000.0]
 ['Sweden' 38.0 65000.0]]


In [10]:
print(y)

['No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No']


In [11]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [12]:
print(x)

[['Netherland' 40.0 75000.0]
 ['England' 32.0 54000.0]
 ['Sweden' 25.0 55000.0]
 ['Scotland' 36.0 60000.0]
 ['England' 50.0 66111.11111111111]
 ['Netherland' 37.0 57000.0]
 ['Sweden' 38.44444444444444 59000.0]
 ['Scotland' 46.0 80000.0]
 ['England' 42.0 90000.0]
 ['Sweden' 38.0 65000.0]]


In [18]:
from math import remainder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [19]:
print(x)

[[0.0 1.0 0.0 0.0 40.0 75000.0]
 [1.0 0.0 0.0 0.0 32.0 54000.0]
 [0.0 0.0 0.0 1.0 25.0 55000.0]
 [0.0 0.0 1.0 0.0 36.0 60000.0]
 [1.0 0.0 0.0 0.0 50.0 66111.11111111111]
 [0.0 1.0 0.0 0.0 37.0 57000.0]
 [0.0 0.0 0.0 1.0 38.44444444444444 59000.0]
 [0.0 0.0 1.0 0.0 46.0 80000.0]
 [1.0 0.0 0.0 0.0 42.0 90000.0]
 [0.0 0.0 0.0 1.0 38.0 65000.0]]


In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [21]:
print(y)

[0 0 1 1 0 1 1 0 1 0]


In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [24]:
print(x_train)

[[0.0 0.0 0.0 1.0 38.44444444444444 59000.0]
 [1.0 0.0 0.0 0.0 50.0 66111.11111111111]
 [0.0 1.0 0.0 0.0 40.0 75000.0]
 [0.0 0.0 1.0 0.0 36.0 60000.0]
 [1.0 0.0 0.0 0.0 32.0 54000.0]
 [0.0 0.0 1.0 0.0 46.0 80000.0]
 [1.0 0.0 0.0 0.0 42.0 90000.0]
 [0.0 1.0 0.0 0.0 37.0 57000.0]]


In [27]:
print(x_test)

[[0.0 0.0 0.0 1.0 25.0 55000.0]
 [0.0 0.0 0.0 1.0 38.0 65000.0]]


In [28]:
print(y_train)

[1 0 0 1 0 0 1 1]


In [29]:
print(y_test)

[1 0]


In [40]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [41]:
print(x_train)

[[0.0 0.0 0.0 2.6457513110645903 -0.3229736956232972 -0.7232030130649898]
 [1.0 0.0 0.0 -0.37796447300922714 1.826739222445367 -0.1278976389664775]
 [0.0 1.0 0.0 -0.37796447300922714 -0.033589264344822914
  0.6162340786566632]
 [0.0 0.0 1.0 -0.37796447300922714 -0.7777206590608987
  -0.6394881948323865]
 [1.0 0.0 0.0 -0.37796447300922714 -1.5218520537769744
  -1.1417771042280063]
 [0.0 0.0 1.0 -0.37796447300922714 1.0826078277292912 1.03480816981968]
 [1.0 0.0 0.0 -0.37796447300922714 0.338476433013215 1.8719563521457132]
 [0.0 1.0 0.0 -0.37796447300922714 -0.5916878103818798
  -0.8906326495301964]]


In [42]:
print(x_test)

[[0.0 0.0 0.0 2.6457513110645903 -2.824081994530107 -1.058062285995403]
 [0.0 0.0 0.0 2.6457513110645903 -0.40565496170286086
  -0.22091410366936992]]
